USE [ReactiveInvoice]
GO
/****** Object:  Table [dbo].[INVOICE]    Script Date: 26.11.2024 г. 10:45:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE](
	[INVOICE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[PARTNER_ID] [numeric](18, 0) NOT NULL,
	[INVOCIE_NO] [varchar](10) NOT NULL,
	[INVOCIE_DATE] [date] NOT NULL,
	[INVOICE_TYPE] [numeric](18, 0) NOT NULL,
	[INVOICE_] [date] NOT NULL,
	[INVOICE_STATUS] [char](1) NOT NULL,
	[INVOICE_VALUE] [numeric](10, 2) NOT NULL,
	[INVOICE_NOTE] [varchar](400) NULL,
 CONSTRAINT [PK_INVOICE] PRIMARY KEY CLUSTERED 
(
	[INVOICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICE_TYPE]    Script Date: 26.11.2024 г. 10:45:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE_TYPE](
	[TYPE_ID] [numeric](18, 0) NOT NULL,
	[TYPE_NAME] [varchar](20) NOT NULL,
 CONSTRAINT [PK_INVOICE_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTNER]    Script Date: 26.11.2024 г. 10:45:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTNER](
	[PARTNER_ID] [numeric](18, 0) NOT NULL,
	[PARTNER_NAME] [varchar](50) NULL,
	[PARTNER_SURNAME] [varchar](50) NULL,
	[PARTNER_LASTNAME] [varchar](50) NULL,
	[PARTNERT_FULLNAME] [varchar](100) NULL,
	[PARTNER_EGN] [varchar](10) NULL,
	[PARTNER_BULSTAT] [varchar](13) NULL,
	[PARTNER_EMAIL] [varchar](100) NULL,
	[PARTNER_PHONE] [varchar](10) NULL,
	[PARTNER_ADDRESS] [varchar](100) NULL,
 CONSTRAINT [PK_PARTNER] PRIMARY KEY CLUSTERED 
(
	[PARTNER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENTS]    Script Date: 26.11.2024 г. 10:45:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENTS](
	[PAYMENT_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[INVOICE_ID] [numeric](18, 0) NULL,
	[PAYMENT_DATE] [date] NOT NULL,
	[PAYMENT_VALUE] [numeric](10, 2) NOT NULL,
 CONSTRAINT [PK_PAYMENTS] PRIMARY KEY CLUSTERED 
(
	[PAYMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 26.11.2024 г. 10:45:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[Id] [nvarchar](40) NOT NULL,
	[FirstName] [nvarchar](40) NULL,
	[LastName] [nvarchar](40) NULL,
	[Username] [nvarchar](40) NULL,
	[Password] [nvarchar](40) NULL,
	[Role] [nvarchar](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_REFERENCE_INVOICE_] FOREIGN KEY([INVOICE_TYPE])
REFERENCES [dbo].[INVOICE_TYPE] ([TYPE_ID])
GO
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK_INVOICE_REFERENCE_INVOICE_]
GO
ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_REFERENCE_PARTNER] FOREIGN KEY([PARTNER_ID])
REFERENCES [dbo].[PARTNER] ([PARTNER_ID])
GO
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK_INVOICE_REFERENCE_PARTNER]
GO
ALTER TABLE [dbo].[PAYMENTS]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENTS_REFERENCE_INVOICE] FOREIGN KEY([INVOICE_ID])
REFERENCES [dbo].[INVOICE] ([INVOICE_ID])
GO
ALTER TABLE [dbo].[PAYMENTS] CHECK CONSTRAINT [FK_PAYMENTS_REFERENCE_INVOICE]
GO
